// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package userapp_admin

import (
	"week04/internal/userapp/biz"
	"week04/internal/userapp/data"
)

// Injectors from wire.go:

func InitUserBiz() *biz.UserBiz {
	userRepo := data.NewUserRepo()
	userBiz := biz.NewUserBiz(userRepo)
	return userBiz
}
